# Generated by Django 4.0.4 on 2022-04-29 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('taux_tva', models.FloatField()),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('est_complete', models.BooleanField(default=False)),
                ('id_utilisateur', models.OneToOneField(db_column='id_utilisateur', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('id', 'id_utilisateur')},
            },
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=1000)),
                ('abreviation', models.CharField(max_length=100)),
                ('diminutif', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=1000)),
                ('prix', models.FloatField()),
                ('stock', models.IntegerField()),
                ('description', models.CharField(max_length=10000)),
                ('image', models.URLField(max_length=1000)),
                ('achetable', models.BooleanField(default=True)),
                ('categorie', models.ForeignKey(db_column='id_categorie', on_delete=django.db.models.deletion.DO_NOTHING, to='store.categorie')),
                ('marque', models.ForeignKey(db_column='id_marque', on_delete=django.db.models.deletion.DO_NOTHING, to='store.marque')),
                ('type', models.ForeignKey(db_column='id_type', on_delete=django.db.models.deletion.DO_NOTHING, to='store.type')),
            ],
        ),
        migrations.CreateModel(
            name='Commande_Produit',
            fields=[
                ('commande', models.OneToOneField(db_column='id_commande', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='store.commande')),
                ('quantite', models.IntegerField()),
                ('produit', models.OneToOneField(db_column='id_produit', on_delete=django.db.models.deletion.DO_NOTHING, to='store.produit')),
            ],
            options={
                'unique_together': {('commande', 'produit')},
            },
        ),
    ]
