# Generated by Django 4.0.4 on 2022-05-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_produit_quantite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='abreviation',
            new_name='mesure',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='diminutif',
            new_name='mesure_petit',
        ),
        migrations.AddField(
            model_name='type',
            name='unite_mesure',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='type',
            name='unite_mesure_petit',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
