# Generated by Django 4.0.4 on 2022-05-23 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_abreviation_type_mesure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande_produit',
            name='commande',
        ),
        migrations.RemoveField(
            model_name='commande_produit',
            name='produit',
        ),
        migrations.DeleteModel(
            name='Commande',
        ),
        migrations.DeleteModel(
            name='Commande_Produit',
        ),
    ]
