# Generated by Django 4.0.4 on 2022-05-23 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0004_alter_commande_produit_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('est_complete', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(blank=True, db_column='id_utilisateur', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commande_Produit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.IntegerField()),
                ('commande', models.ForeignKey(blank=True, db_column='id_commande', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.commande')),
                ('produit', models.ForeignKey(blank=True, db_column='id_produit', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.produit')),
            ],
        ),
    ]
